export const INCREASE_ENTHUSIASM = "INCREASE_ENTHUSIASM";
export type INCREASE_ENTHUSIASM = typeof INCREASE_ENTHUSIASM;

export const DECREASE_ENTHUSIASM = "DECREASE_ENTHUSIASM";
export type DECREASE_ENTHUSIASM = typeof DECREASE_ENTHUSIASM;