export const INCREASE_ENTHUSIASM = "INCREASE_ENTHUSIASM";
export type INCREASE_ENTHUSIASM = typeof INCREASE_ENTHUSIASM;

export const DECREASE_ENTHUSIASM = "DECREASE_ENTHUSIASM";
export type DECREASE_ENTHUSIASM = typeof DECREASE_ENTHUSIASM;

export const GET_USERNAME = "GET_USERNAME";
export type GET_USERNAME = typeof GET_USERNAME;

export const GET_USERNAME_ERR = "GET_USERNAME_ERR";
export type GET_USERNAME_ERR = typeof GET_USERNAME_ERR;